[package]
name = "rust-sf-sync"
version = "0.1.0"
authors = ["dan"]

[dependencies]
hyper = "0.11"
hyper-tls = "0.1.0"
futures = "0.1.14"
tokio-core = "0.1.8"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
chrono = "0.4"
time = "0.1"
postgres = "0.14"